### PR TITLE
Fixes #36: Add Specialization table.

### LINKED ISSUE #36: [Feature Request]: Create Specialization Model
### Is your feature request related to a problem? Please describe.

We need Specialization Model in DB.

### Describe the solution you'd like

Refer to https://github.com/rt4914/KlinicCon-Backend/wiki/DB-Design

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by aniketpatidar**
Resolves #36 

---

### Description

This pull request introduces creating the `specializations` table in the database. Table includes the following attributes:
**Specializations table**:
   - `name` (string, unique, not null)
   - Timestamps

---

### Type of Change
- [x] Feature

---

### How to test this PR?
Steps to test the migrations:

1. Run `rails db:migrate` to apply the migration.
2. Verify the `specializations` table is created in the database with the `name` columns, timestamps.
3. Attempt to insert records with duplicate names in table to ensure the unique constraint is functioning as expected.

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
Update title to`Fixes #36 : Add ...`

Also, once your previous PR gets merged, you can update this branch assign it back to me.

**Comment by aniketpatidar** [comment]
> Update title to`Fixes #36 : Add ...`
> 
 Also, once your previous PR gets merged, you can update this branch and assign it back to me.

I will make the changes you suggested!

**Comment by rt4914** [comment]
@aniketpatidar You can update this now.

**Review by rt4914 — APPROVED** [review]

**Comment by aniketpatidar** [comment]
Firstly generated migration 
rails generate model Specialization name:string:uniq

Then added null false

class CreateSpecializations < ActiveRecord::Migration[6.1]
  def change
    create_table :specializations do |t|
      t.string :name, null: false

      t.timestamps
    end

    add_index :specializations, :name, unique: true
  end
end

Then run rails db:migrate

**Pull request merged**
